$x^{y^{z^{v^k}}}$ mi **casa** bonita


ping elpais.es

In [1]:
ping elpais.es

SyntaxError: invalid syntax (<ipython-input-1-393f22a26152>, line 1)

In [3]:
!ping elpais.es



Haciendo ping a elpais.es [91.216.63.241] con 32 bytes de datos:
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.

Estad¡sticas de ping para 91.216.63.241:
    Paquetes: enviados = 4, recibidos = 0, perdidos = 4
    (100% perdidos),


In [4]:
!dir

 El volumen de la unidad C es OS
 El n£mero de serie del volumen es: 3809-48C8

 Directorio de C:\Users\JuanJose\jj\GitHub\Ingenieria-Logistica-ULL

22/01/2019  17:45    <DIR>          .
22/01/2019  17:45    <DIR>          ..
22/01/2019  17:41    <DIR>          .ipynb_checkpoints
21/01/2019  08:30            20.068 CarlosGarciaGonzalez.ipynb
22/01/2019  17:45               676 curso.ipynb
02/01/2019  14:49           249.420 logistica.ipynb
22/01/2019  17:30               655 Untitled.ipynb
               4 archivos        270.819 bytes
               3 dirs  66.056.716.288 bytes libres


In [5]:
os.path.dirname?

Object `os.path.dirname` not found.


In [15]:
import random
random.seed?

In [14]:
import gurobipy
gurobipy.optimize?


Object `gurobipy.optimize` not found.


In [39]:
%%writefile "micuadrado.py"
x = 5
print (x*2)

Overwriting micuadrado.py


In [42]:
#load "micuadrado.py"


10


In [43]:
%run "micuadrado.py"

10


In [45]:
import numpy
%timeit numpy.random.normal(size=100)

12 µs ± 76.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%timeit
numpy.random.normal(size=100)
numpy.random.uniform(size=100)

array([0.04758421, 0.65813424, 0.3860801 , 0.82686004, 0.46533518,
       0.78283421, 0.35785843, 0.69185825, 0.32776625, 0.27435479,
       0.56708493, 0.59284601, 0.23506919, 0.09648759, 0.95910604,
       0.17947301, 0.47055526, 0.57074932, 0.61696222, 0.5122144 ,
       0.93111295, 0.83057728, 0.48172606, 0.88032126, 0.27898622,
       0.46347077, 0.73886101, 0.21359202, 0.74869436, 0.96761845,
       0.98097846, 0.28003511, 0.70408278, 0.77410501, 0.28523291,
       0.50355717, 0.05620835, 0.13243006, 0.31677594, 0.36144513,
       0.98808298, 0.81366958, 0.89675729, 0.7245335 , 0.38111222,
       0.41681435, 0.83949316, 0.31580029, 0.52962189, 0.10571715,
       0.61484746, 0.2695176 , 0.98826776, 0.44488643, 0.42943957,
       0.76313425, 0.92242153, 0.13356589, 0.82483594, 0.91060933,
       0.45037868, 0.54450587, 0.84463514, 0.84497636, 0.02059409,
       0.53378231, 0.57765449, 0.93473541, 0.75699797, 0.49609104,
       0.47870119, 0.40462704, 0.21127184, 0.10508689, 0.64045

In [55]:
import cmath
z1 = complex(-3,7)
z2 = complex(2,-5)
print( "fase=",cmath.phase(z1),", modulo=",abs(z1))
print( "fase=",cmath.phase(z2),", modulo=",abs(z2))

fase= 1.97568811307998 , modulo= 7.615773105863909
fase= -1.1902899496825317 , modulo= 5.385164807134504


In [ ]:
cadena = "Happiness is a way of travel. Not a destination."

In [68]:
cadena = "Happiness is a way of travel. Not a destination."
print( cadena[: len(cadena)//2+5 ] )
print( cadena[ -len(cadena)//2+5 :: ] )


Happiness is a way of travel.
 Not a destination.


In [70]:
chr(128522)

'😊'

In [71]:
ord("😊")

128522

In [72]:
os.linesep

'\r\n'

In [ ]:
palabras = "Cobalt, Silver, Platinum"
valores  = "27, 47, 78"
lista_palabras = palabras.split(", ")
lista_valores  = valores.split(", ")
dic = {}
for i in range(len(palabras) ) :
     dic.( )

In [10]:
gravity = [ 2.8 , 8.9 , 9.8 , 3.71 , 22.8 , 9.1 , 7.8 , 11.00 ]
media = 0
for g in gravity:
    media += g
media = media / len(gravity)

varianza = 0
for g in gravity:
    varianza += (g - media)**2
varianza = ( varianza / len(gravity) )**0.5

print(media,",",varianza)

9.488750000000001 , 5.71241069405028


In [23]:
import numpy as np
array1 = np.array([ 88, 23, 39, 41])
array2 = np.array([ [76.4, 21.7, 38.4] , [41.2, 52.8] ])
array3 = np.array([ [12], ['a'] , [9], ["b"] ])
def imprime(array):
    print( array.shape )
    print( array.ndim )
    print( type(array) )
imprime(array1)
imprime(array2)
imprime(array3)

(4,)
1
<class 'numpy.ndarray'>
(2,)
1
<class 'numpy.ndarray'>
(4, 1)
2
<class 'numpy.ndarray'>


In [25]:
diagonal = np.diag( [ i in range(50)] )
diagonal

array([[ True]])

In [30]:
X = np.linspace(1,10,size(20,5))

NameError: name 'size' is not defined

In [43]:
X= np.array([0,1,2,3,4,5,6,7,8,9])
X[ X % 2 != 0 ]


array([1, 3, 5, 7, 9])

In [45]:
Y= np.array([0,1,2,3,4,5,6,7,8,9])
Y[ X % 2 ]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
M = np.random.rand()